name: MasterDeployCI
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
        git config --global user.email "akhilrana0001@gmail.com"
        git config --global user.name "akhil-rana"
        git remote set-url origin https://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@github.com/akhil-rana/peerivate.git
      run: npm run deploy
    - name: Updating Domain
      run: echo "Update domain"
